# Generated by Django 2.1.4 on 2019-04-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=15)),
                ('bank_id', models.IntegerField(max_length=15)),
                ('branch', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
            ],
        ),
    ]
